-- file ~/.config/wezterm/colors/ykm22_wez_colors.lua
local dir = vim.loop.os_homedir() .. "/.config/wezterm/colors"
local filepath = dir .. "/ykm22_wez_colors.lua"
local file = io.open(filepath, "r")

if file then
    file:close()
else
    if not vim.loop.fs_stat(dir) then
        vim.fn.system('mkdir -p "' .. dir .. '"')
    end
    vim.fn.system(
        "wget -O "
            .. filepath
            .. " https://raw.githubusercontent.com/yakumo22-r/wezterm-config/master/colors/ykm22_wez_colors.lua"
    )
end


local originalPath = package.path
package.path = filepath .. ";" .. package.path

---@type COLORS
local result = require("ykm22_wez_colors")
package.path = originalPath

local ykm22 = {}

ykm22.config = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
        strings = false,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    invert_intend_guides = false,
    inverse = true,
    contrast = "",
    overrides = {},
    dim_inactive = false,
    transparent_mode = true,
}

-- theme
local p = result
-- get a hex list of gruvbox colors based on current bg and constrast config
local function get_colors()
    local config = ykm22.config

    local bg = vim.o.background
    local contrast = config.contrast

    local color_groups = {
        dark = {
            bg0 = p.dark0,
            bg1 = p.dark1,
            bg2 = p.dark2,
            bg3 = p.dark3,
            bg4 = p.dark4,
            fg0 = p.light0,
            fg1 = p.light1,
            fg2 = p.light2,
            fg3 = p.light3,
            fg4 = p.light4,
            red = p.bright_red,
            green = p.bright_green,
            yellow = p.bright_yellow,
            blue = p.bright_blue,
            purple = p.bright_purple,
            aqua = p.bright_aqua,
            orange = p.bright_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.dark_red,
            dark_green = p.dark_green,
            dark_aqua = p.dark_aqua,
            gray = p.gray,

            warm_light = p.warm_light,
        },
        light = {
            bg0 = p.light0,
            bg1 = p.light1,
            bg2 = p.light2,
            bg3 = p.light3,
            bg4 = p.light4,
            fg0 = p.dark0,
            fg1 = p.dark1,
            fg2 = p.dark2,
            fg3 = p.dark3,
            fg4 = p.dark4,
            red = p.faded_red,
            green = p.faded_green,
            yellow = p.faded_yellow,
            blue = p.faded_blue,
            purple = p.faded_purple,
            aqua = p.faded_aqua,
            orange = p.faded_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.light_red,
            dark_green = p.light_green,
            dark_aqua = p.light_aqua,
            gray = p.gray,
        },
    }

    if contrast ~= nil and contrast ~= "" then
        color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
        color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
        color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
        color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
    end

    return color_groups[bg]
end

local function get_groups()
    local colors = get_colors()
    local config = ykm22.config

    if config.terminal_colors then
        for index, value in ipairs(p.term) do
            vim.g["terminal_color_" .. index - 1] = value
        end
    end

    local groups = {
        ykm22Fg0 = { fg = colors.fg0 },
        ykm22Fg1 = { fg = colors.fg1 },
        ykm22Fg2 = { fg = colors.fg2 },
        ykm22Fg3 = { fg = colors.fg3 },
        ykm22Fg4 = { fg = colors.fg4 },
        ykm22Gray = { fg = colors.gray },
        ykm22Bg0 = { fg = colors.bg0 },
        ykm22Bg1 = { fg = colors.bg1 },
        ykm22Bg2 = { fg = colors.bg2 },
        ykm22Bg3 = { fg = colors.bg3 },
        ykm22Bg4 = { fg = colors.bg4 },
        ykm22Red = { fg = colors.red, bg = nil },
        ykm22RedBold = { fg = colors.red, bold = config.bold },
        ykm22Green = { fg = colors.green },
        ykm22GreenBold = { fg = colors.green, bold = config.bold },
        ykm22Yellow = { fg = colors.yellow },
        ykm22YellowBold = { fg = colors.yellow, bold = config.bold },
        ykm22Blue = { fg = colors.blue },
        ykm22BlueBold = { fg = colors.blue, bold = config.bold },
        ykm22Purple = { fg = colors.purple },
        ykm22PurpleBold = { fg = colors.purple, bold = config.bold },
        ykm22Aqua = { fg = colors.aqua },
        ykm22AquaBold = { fg = colors.aqua, bold = config.bold },
        ykm22Orange = { fg = colors.orange },
        ykm22OrangeBold = { fg = colors.orange, bold = config.bold },
        ykm22RedSign = config.transparent_mode
                and { fg = colors.red, reverse = config.invert_signs }
            or {
                fg = colors.red,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22GreenSign = config.transparent_mode
                and { fg = colors.green, reverse = config.invert_signs }
            or {
                fg = colors.green,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22YellowSign = config.transparent_mode
                and { fg = colors.yellow, reverse = config.invert_signs }
            or {
                fg = colors.yellow,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22BlueSign = config.transparent_mode
                and { fg = colors.blue, reverse = config.invert_signs }
            or {
                fg = colors.blue,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22PurpleSign = config.transparent_mode
                and { fg = colors.purple, reverse = config.invert_signs }
            or {
                fg = colors.purple,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22AquaSign = config.transparent_mode
                and { fg = colors.aqua, reverse = config.invert_signs }
            or {
                fg = colors.aqua,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22OrangeSign = config.transparent_mode
                and { fg = colors.orange, reverse = config.invert_signs }
            or {
                fg = colors.orange,
                bg = colors.bg1,
                reverse = config.invert_signs,
            },
        ykm22RedUnderline = { undercurl = config.undercurl, sp = colors.red },
        ykm22GreenUnderline = {
            undercurl = config.undercurl,
            sp = colors.green,
        },
        ykm22YellowUnderline = {
            undercurl = config.undercurl,
            sp = colors.yellow,
        },
        ykm22BlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
        ykm22PurpleUnderline = {
            undercurl = config.undercurl,
            sp = colors.purple,
        },
        ykm22AquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
        ykm22OrangeUnderline = {
            undercurl = config.undercurl,
            sp = colors.orange,
        },
        Normal = config.transparent_mode and { fg = colors.fg1, bg = nil }
            or { fg = colors.fg1, bg = colors.bg0 },
        NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil }
            or { fg = colors.fg1, bg = colors.bg1 },
        NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 }
            or { link = "Normal" },
        CursorLine = { bg = p.dark0 },
        CursorColumn = { bg = colors.bg1 },
        TabLineSel = {
            fg = p.light0,
            bg = p.dark2,
        },
        TabLine = {
            fg = p.light2,
            bg = p.dark0,
        },
        TabLineFill = {
            fg = p.light2,
            bg = p.dark0
        },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue },
        CursorLineNr = {},
        NonText = { link = "ykm22Bg2" },
        SpecialKey = { link = "ykm22Fg4" },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },

        VertSplit = { fg = colors.yellow, bg = colors.bg1 },
        Search = {
            fg = colors.yellow,
            bg = colors.bg0,
            reverse = config.inverse,
        },
        IncSearch = {
            fg = colors.orange,
            bg = colors.bg0,
            reverse = config.inverse,
        },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "ykm22Purple" },
        Underlined = { fg = colors.blue, underline = config.underline },
        StatusLine = {
            fg = colors.bg2,
            bg = colors.fg1,
            reverse = config.inverse,
        },
        StatusLineNC = {
            fg = colors.bg1,
            bg = colors.fg4,
            reverse = config.inverse,
        },
        WinBar = { fg = colors.fg4, bg = colors.bg0 },
        WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
        WinSeparator = config.transparent_mode
                and { fg = colors.bg3, bg = nil }
            or { fg = colors.bg3, bg = colors.bg0 },
        WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
        Directory = { link = "ykm22BlueBold" },
        Title = { link = "ykm22GreenBold" },
        ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MoreMsg = { link = "ykm22YellowBold" },
        ModeMsg = { link = "ykm22YellowBold" },
        Question = { link = "ykm22OrangeBold" },
        WarningMsg = { link = "ykm22RedBold" },
        LineNr = { fg = colors.bg4 },
        SignColumn = config.transparent_mode and { bg = nil }
            or { bg = colors.bg1 },
        Folded = {
            fg = colors.gray,
            bg = colors.bg1,
            italic = config.italic.folds,
        },
        FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil }
            or { fg = colors.gray, bg = colors.bg1 },
        Cursor = { reverse = config.inverse },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { fg = p.bright_red },
        Comment = { fg = colors.fg4, italic = config.italic.comments },
        Todo = {
            fg = colors.yellow,
            bg = colors.dark_red,
            bold = config.bold,
            -- italic = config.italic.comments,
            undercurl = true,
            -- reverse = config.reverse,
        },
        Done = {
            fg = colors.orange,
            bold = config.bold,
            italic = config.italic.comments,
        },
        Error = {
            fg = colors.red,
            bold = config.bold,
            reverse = config.inverse,
        },
        Statement = { link = "ykm22Red" },
        Conditional = { link = "ykm22Red" },
        Repeat = { link = "ykm22Red" },
        Label = { link = "ykm22Red" },
        Exception = { link = "ykm22Red" },
        Operator = { fg = p.light_red, italic = config.italic.operators },
        Keyword = { link = "ykm22Red", bg = colors.bg2 },
        Identifier = { fg = "#ffceb0" },
        Function = { link = "ykm22Orange" },
        PreProc = { link = "ykm22Red" },
        Include = { link = "ykm22Red" },
        Define = { link = "ykm22Aqua" },
        Macro = { fg = p.light_red },
        PreCondit = { link = "ykm22Aqua" },
        Constant = { link = "ykm22Purple" },
        Character = { link = "ykm22Purple" },
        String = { fg = colors.warm_light, italic = config.italic.strings },
        Number = { link = "ykm22Purple" },
        Float = { link = "ykm22Purple" },
        Type = { link = "ykm22Yellow" },
        StorageClass = { link = "ykm22Orange" },
        Structure = { link = "ykm22Red" },
        Typedef = { link = "ykm22Yellow" },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        DiffDelete = { bg = colors.dark_red },
        DiffAdd = { bg = colors.dark_green },
        DiffChange = { bg = colors.dark_aqua },
        DiffText = { bg = colors.yellow, fg = colors.bg0 },
        SpellCap = { link = "ykm22BlueUnderline" },
        SpellBad = { link = "ykm22RedUnderline" },
        SpellLocal = { link = "ykm22AquaUnderline" },
        SpellRare = { link = "ykm22PurpleUnderline" },
        Whitespace = { fg = colors.bg3 },
        DiagnosticError = { link = "ykm22Red" },
        DiagnosticSignError = { link = "ykm22RedSign" },
        DiagnosticUnderlineError = { link = "ykm22RedUnderline" },
        DiagnosticWarn = { link = "ykm22Yellow" },
        DiagnosticSignWarn = { link = "ykm22YellowSign" },
        DiagnosticUnderlineWarn = { link = "ykm22YellowUnderline" },
        DiagnosticInfo = { link = "ykm22Blue" },
        DiagnosticSignInfo = { link = "ykm22BlueSign" },
        DiagnosticUnderlineInfo = { link = "ykm22BlueUnderline" },
        DiagnosticHint = { link = "ykm22Aqua" },
        DiagnosticSignHint = { link = "ykm22AquaSign" },
        DiagnosticUnderlineHint = { link = "ykm22AquaUnderline" },
        DiagnosticFloatingError = { link = "ykm22Red" },
        DiagnosticFloatingWarn = { link = "ykm22Orange" },
        DiagnosticFloatingInfo = { link = "ykm22Blue" },
        DiagnosticFloatingHint = { link = "ykm22Aqua" },
        DiagnosticVirtualTextError = { link = "ykm22Red" },
        DiagnosticVirtualTextWarn = { link = "ykm22Yellow" },
        DiagnosticVirtualTextInfo = { link = "ykm22Blue" },
        DiagnosticVirtualTextHint = { link = "ykm22Aqua" },
        DiagnosticOk = { link = "ykm22GreenSign" },
        LspReferenceRead = { link = "ykm22YellowBold" },
        LspReferenceText = { link = "ykm22YellowBold" },
        LspReferenceWrite = { link = "ykm22OrangeBold" },
        LspCodeLens = { link = "ykm22Gray" },
        LspSignatureActiveParameter = { link = "Search" },
        gitcommitSelectedFile = { link = "ykm22Green" },
        gitcommitDiscardedFile = { link = "ykm22Red" },
        GitSignsAdd = { link = "ykm22Green" },
        GitSignsChange = { link = "ykm22Aqua" },
        GitSignsDelete = { link = "ykm22Red" },
        NvimTreeSymlink = { fg = colors.neutral_aqua },
        NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
        NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
        NvimTreeFileIcon = { fg = colors.light2 },
        NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
        NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
        NvimTreeSpecialFile = {
            fg = colors.neutral_yellow,
            bold = true,
            underline = true,
        },
        NvimTreeImageFile = { fg = colors.neutral_purple },
        NvimTreeIndentMarker = { fg = colors.dark3 },
        NvimTreeGitDirty = { fg = colors.neutral_yellow },
        NvimTreeGitStaged = { fg = colors.neutral_yellow },
        NvimTreeGitMerge = { fg = colors.neutral_purple },
        NvimTreeGitRenamed = { fg = colors.neutral_purple },
        NvimTreeGitNew = { fg = colors.neutral_yellow },
        NvimTreeGitDeleted = { fg = colors.neutral_red },
        NvimTreeWindowPicker = { bg = colors.aqua },
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "ykm22RedSign" },
        StartifyBracket = { link = "ykm22Fg3" },
        StartifyFile = { link = "ykm22Fg1" },
        StartifyNumber = { link = "ykm22Blue" },
        StartifyPath = { link = "ykm22Gray" },
        StartifySlash = { link = "ykm22Gray" },
        StartifySection = { link = "ykm22Yellow" },
        StartifySpecial = { link = "ykm22Bg2" },
        StartifyHeader = { link = "ykm22Orange" },
        StartifyFooter = { link = "ykm22Bg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },
        DirvishPathTail = { link = "ykm22Aqua" },
        DirvishArg = { link = "ykm22Yellow" },
        netrwDir = { link = "ykm22Aqua" },
        netrwClassify = { link = "ykm22Aqua" },
        netrwLink = { link = "ykm22Gray" },
        netrwSymLink = { link = "ykm22Fg1" },
        netrwExe = { link = "ykm22Yellow" },
        netrwComment = { link = "ykm22Gray" },
        netrwList = { link = "ykm22Blue" },
        netrwHelpCmd = { link = "ykm22Aqua" },
        netrwCmdSep = { link = "ykm22Fg3" },
        netrwVersion = { link = "ykm22Green" },
        NERDTreeDir = { link = "ykm22Aqua" },
        NERDTreeDirSlash = { link = "ykm22Aqua" },
        NERDTreeOpenable = { link = "ykm22Orange" },
        NERDTreeClosable = { link = "ykm22Orange" },
        NERDTreeFile = { link = "ykm22Fg1" },
        NERDTreeExecFile = { link = "ykm22Yellow" },
        NERDTreeUp = { link = "ykm22Gray" },
        NERDTreeCWD = { link = "ykm22Green" },
        NERDTreeHelp = { link = "ykm22Fg1" },
        NERDTreeToggleOn = { link = "ykm22Green" },
        NERDTreeToggleOff = { link = "ykm22Red" },
        CocErrorSign = { link = "ykm22RedSign" },
        CocWarningSign = { link = "ykm22OrangeSign" },
        CocInfoSign = { link = "ykm22BlueSign" },
        CocHintSign = { link = "ykm22AquaSign" },
        CocErrorFloat = { link = "ykm22Red" },
        CocWarningFloat = { link = "ykm22Orange" },
        CocInfoFloat = { link = "ykm22Blue" },
        CocHintFloat = { link = "ykm22Aqua" },
        CocDiagnosticsError = { link = "ykm22Red" },
        CocDiagnosticsWarning = { link = "ykm22Orange" },
        CocDiagnosticsInfo = { link = "ykm22Blue" },
        CocDiagnosticsHint = { link = "ykm22Aqua" },
        CocSelectedText = { link = "ykm22Red" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "ykm22Gray" },
        CocErrorHighlight = { link = "ykm22RedUnderline" },
        CocWarningHighlight = { link = "ykm22OrangeUnderline" },
        CocInfoHighlight = { link = "ykm22BlueUnderline" },
        CocHintHighlight = { link = "ykm22AquaUnderline" },
        TelescopeNormal = { link = "ykm22Fg1" },
        TelescopeSelection = { link = "ykm22OrangeBold" },
        TelescopeSelectionCaret = { link = "ykm22Red" },
        TelescopeMultiSelection = { link = "ykm22Gray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "ykm22Blue" },
        TelescopePromptPrefix = { link = "ykm22Red" },
        TelescopePrompt = { link = "TelescopeNormal" },
        CmpItemAbbr = { link = "ykm22Fg0" },
        CmpItemAbbrDeprecated = { link = "ykm22Fg1" },
        CmpItemAbbrMatch = { link = "ykm22BlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "ykm22BlueUnderline" },
        CmpItemMenu = { link = "ykm22Gray" },
        CmpItemKindText = { link = "ykm22Orange" },
        CmpItemKindVariable = { link = "ykm22Orange" },
        CmpItemKindMethod = { link = "ykm22Blue" },
        CmpItemKindFunction = { link = "ykm22Blue" },
        CmpItemKindConstructor = { link = "ykm22Yellow" },
        CmpItemKindUnit = { link = "ykm22Blue" },
        CmpItemKindField = { link = "ykm22Blue" },
        CmpItemKindClass = { link = "ykm22Yellow" },
        CmpItemKindInterface = { link = "ykm22Yellow" },
        CmpItemKindModule = { link = "ykm22Blue" },
        CmpItemKindProperty = { link = "ykm22Blue" },
        CmpItemKindValue = { link = "ykm22Orange" },
        CmpItemKindEnum = { link = "ykm22Yellow" },
        CmpItemKindOperator = { link = "ykm22Yellow" },
        CmpItemKindKeyword = { link = "ykm22Purple" },
        CmpItemKindEvent = { link = "ykm22Purple" },
        CmpItemKindReference = { link = "ykm22Purple" },
        CmpItemKindColor = { link = "ykm22Purple" },
        CmpItemKindSnippet = { link = "ykm22Green" },
        CmpItemKindFile = { link = "ykm22Blue" },
        CmpItemKindFolder = { link = "ykm22Blue" },
        CmpItemKindEnumMember = { link = "ykm22Aqua" },
        CmpItemKindConstant = { link = "ykm22Orange" },
        CmpItemKindStruct = { link = "ykm22Yellow" },
        CmpItemKindTypeParameter = { link = "ykm22Yellow" },
        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "ykm22Orange" },
        diffNewFile = { link = "ykm22Yellow" },
        diffOldFile = { link = "ykm22Orange" },
        diffLine = { link = "ykm22Blue" },
        diffIndexLine = { link = "diffChanged" },
        NavicIconsFile = { link = "ykm22Blue" },
        NavicIconsModule = { link = "ykm22Orange" },
        NavicIconsNamespace = { link = "ykm22Blue" },
        NavicIconsPackage = { link = "ykm22Aqua" },
        NavicIconsClass = { link = "ykm22Yellow" },
        NavicIconsMethod = { link = "ykm22Blue" },
        NavicIconsProperty = { link = "ykm22Aqua" },
        NavicIconsField = { link = "ykm22Purple" },
        NavicIconsConstructor = { link = "ykm22Blue" },
        NavicIconsEnum = { link = "ykm22Purple" },
        NavicIconsInterface = { link = "ykm22Green" },
        NavicIconsFunction = { link = "ykm22Blue" },
        NavicIconsVariable = { link = "ykm22Purple" },
        NavicIconsConstant = { link = "ykm22Orange" },
        NavicIconsString = { link = "ykm22Green" },
        NavicIconsNumber = { link = "ykm22Orange" },
        NavicIconsBoolean = { link = "ykm22Orange" },
        NavicIconsArray = { link = "ykm22Orange" },
        NavicIconsObject = { link = "ykm22Orange" },
        NavicIconsKey = { link = "ykm22Aqua" },
        NavicIconsNull = { link = "ykm22Orange" },
        NavicIconsEnumMember = { link = "ykm22Yellow" },
        NavicIconsStruct = { link = "ykm22Purple" },
        NavicIconsEvent = { link = "ykm22Yellow" },
        NavicIconsOperator = { link = "ykm22Red" },
        NavicIconsTypeParameter = { link = "ykm22Red" },
        NavicText = { link = "ykm22White" },
        NavicSeparator = { link = "ykm22White" },
        htmlTag = { link = "ykm22AquaBold" },
        htmlEndTag = { link = "ykm22AquaBold" },
        htmlTagName = { link = "ykm22Blue" },
        htmlArg = { link = "ykm22Orange" },
        htmlTagN = { link = "ykm22Fg1" },
        htmlSpecialTagName = { link = "ykm22Blue" },
        htmlLink = { fg = colors.fg4, underline = config.underline },
        htmlSpecialChar = { link = "ykm22Red" },
        htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
        htmlBoldUnderline = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            underline = config.underline,
        },
        htmlBoldItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            italic = true,
        },
        htmlBoldUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            italic = true,
            underline = config.underline,
        },
        htmlUnderline = {
            fg = colors.fg0,
            bg = colors.bg0,
            underline = config.underline,
        },
        htmlUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            italic = true,
            underline = config.underline,
        },
        htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
        xmlTag = { link = "ykm22AquaBold" },
        xmlEndTag = { link = "ykm22AquaBold" },
        xmlTagName = { link = "ykm22Blue" },
        xmlEqual = { link = "ykm22Blue" },
        docbkKeyword = { link = "ykm22AquaBold" },
        xmlDocTypeDecl = { link = "ykm22Gray" },
        xmlDocTypeKeyword = { link = "ykm22Purple" },
        xmlCdataStart = { link = "ykm22Gray" },
        xmlCdataCdata = { link = "ykm22Purple" },
        dtdFunction = { link = "ykm22Gray" },
        dtdTagName = { link = "ykm22Purple" },
        xmlAttrib = { link = "ykm22Orange" },
        xmlProcessingDelim = { link = "ykm22Gray" },
        dtdParamEntityPunct = { link = "ykm22Gray" },
        dtdParamEntityDPunct = { link = "ykm22Gray" },
        xmlAttribPunct = { link = "ykm22Gray" },
        xmlEntity = { link = "ykm22Red" },
        xmlEntityPunct = { link = "ykm22Red" },
        clojureKeyword = { link = "ykm22Blue" },
        clojureCond = { link = "ykm22Orange" },
        clojureSpecial = { link = "ykm22Orange" },
        clojureDefine = { link = "ykm22Orange" },
        clojureFunc = { link = "ykm22Yellow" },
        clojureRepeat = { link = "ykm22Yellow" },
        clojureCharacter = { link = "ykm22Aqua" },
        clojureStringEscape = { link = "ykm22Aqua" },
        clojureException = { link = "ykm22Red" },
        clojureRegexp = { link = "ykm22Aqua" },
        clojureRegexpEscape = { link = "ykm22Aqua" },
        clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
        clojureRegexpMod = { link = "clojureRegexpCharClass" },
        clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
        clojureParen = { link = "ykm22Fg3" },
        clojureAnonArg = { link = "ykm22Yellow" },
        clojureVariable = { link = "ykm22Blue" },
        clojureMacro = { link = "ykm22Orange" },
        clojureMeta = { link = "ykm22Yellow" },
        clojureDeref = { link = "ykm22Yellow" },
        clojureQuote = { link = "ykm22Yellow" },
        clojureUnquote = { link = "ykm22Yellow" },
        cOperator = { link = "ykm22Purple" },
        cPreCondit = {link = "ykm22Red"},
        cType = {link = "ykm22Red"},
        cStructure = { link = "ykm22Red" },
        cStorageClass = { link = "ykm22Red" },
        cDefine = { link = "ykm22Red" },
        cppOperator = { link = "ykm22Purple" },
        cppModifier = { link = "ykm22Red" },
        pythonBuiltin = { link = "ykm22Orange" },
        pythonBuiltinObj = { link = "ykm22Orange" },
        pythonBuiltinFunc = { link = "ykm22Orange" },
        pythonFunction = { link = "ykm22Aqua" },
        pythonDecorator = { link = "ykm22Red" },
        pythonInclude = { link = "ykm22Blue" },
        pythonImport = { link = "ykm22Blue" },
        pythonRun = { link = "ykm22Blue" },
        pythonCoding = { link = "ykm22Blue" },
        pythonOperator = { link = "ykm22Red" },
        pythonException = { link = "ykm22Red" },
        pythonExceptions = { link = "ykm22Purple" },
        pythonBoolean = { link = "ykm22Purple" },
        pythonDot = { link = "ykm22Fg3" },
        pythonConditional = { link = "ykm22Red" },
        pythonRepeat = { link = "ykm22Red" },
        pythonDottedName = { link = "ykm22GreenBold" },
        cssBraces = { link = "ykm22Blue" },
        cssFunctionName = { link = "ykm22Yellow" },
        cssIdentifier = { link = "ykm22Orange" },
        cssClassName = { link = "ykm22Green" },
        cssColor = { link = "ykm22Blue" },
        cssSelectorOp = { link = "ykm22Blue" },
        cssSelectorOp2 = { link = "ykm22Blue" },
        cssImportant = { link = "ykm22Green" },
        cssVendor = { link = "ykm22Fg1" },
        cssTextProp = { link = "ykm22Aqua" },
        cssAnimationProp = { link = "ykm22Aqua" },
        cssUIProp = { link = "ykm22Yellow" },
        cssTransformProp = { link = "ykm22Aqua" },
        cssTransitionProp = { link = "ykm22Aqua" },
        cssPrintProp = { link = "ykm22Aqua" },
        cssPositioningProp = { link = "ykm22Yellow" },
        cssBoxProp = { link = "ykm22Aqua" },
        cssFontDescriptorProp = { link = "ykm22Aqua" },
        cssFlexibleBoxProp = { link = "ykm22Aqua" },
        cssBorderOutlineProp = { link = "ykm22Aqua" },
        cssBackgroundProp = { link = "ykm22Aqua" },
        cssMarginProp = { link = "ykm22Aqua" },
        cssListProp = { link = "ykm22Aqua" },
        cssTableProp = { link = "ykm22Aqua" },
        cssFontProp = { link = "ykm22Aqua" },
        cssPaddingProp = { link = "ykm22Aqua" },
        cssDimensionProp = { link = "ykm22Aqua" },
        cssRenderProp = { link = "ykm22Aqua" },
        cssColorProp = { link = "ykm22Aqua" },
        cssGeneratedContentProp = { link = "ykm22Aqua" },
        javaScriptBraces = { link = "ykm22Fg1" },
        javaScriptFunction = { link = "ykm22Aqua" },
        javaScriptIdentifier = { link = "ykm22Red" },
        javaScriptMember = { link = "ykm22Blue" },
        javaScriptNumber = { link = "ykm22Purple" },
        javaScriptNull = { link = "ykm22Purple" },
        javaScriptParens = { link = "ykm22Fg3" },
        typescriptReserved = { link = "ykm22Aqua" },
        typescriptLabel = { link = "ykm22Aqua" },
        typescriptFuncKeyword = { link = "ykm22Aqua" },
        typescriptIdentifier = { link = "ykm22Orange" },
        typescriptBraces = { link = "ykm22Fg1" },
        typescriptEndColons = { link = "ykm22Fg1" },
        typescriptDOMObjects = { link = "ykm22Fg1" },
        typescriptAjaxMethods = { link = "ykm22Fg1" },
        typescriptLogicSymbols = { link = "ykm22Fg1" },
        typescriptDocSeeTag = { link = "Comment" },
        typescriptDocParam = { link = "Comment" },
        typescriptDocTags = { link = "vimCommentTitle" },
        typescriptGlobalObjects = { link = "ykm22Fg1" },
        typescriptParens = { link = "ykm22Fg3" },
        typescriptOpSymbols = { link = "ykm22Fg3" },
        typescriptHtmlElemProperties = { link = "ykm22Fg1" },
        typescriptNull = { link = "ykm22Purple" },
        typescriptInterpolationDelimiter = { link = "ykm22Aqua" },
        purescriptModuleKeyword = { link = "ykm22Aqua" },
        purescriptModuleName = { link = "ykm22Fg1" },
        purescriptWhere = { link = "ykm22Aqua" },
        purescriptDelimiter = { link = "ykm22Fg4" },
        purescriptType = { link = "ykm22Fg1" },
        purescriptImportKeyword = { link = "ykm22Aqua" },
        purescriptHidingKeyword = { link = "ykm22Aqua" },
        purescriptAsKeyword = { link = "ykm22Aqua" },
        purescriptStructure = { link = "ykm22Aqua" },
        purescriptOperator = { link = "ykm22Blue" },
        purescriptTypeVar = { link = "ykm22Fg1" },
        purescriptConstructor = { link = "ykm22Fg1" },
        purescriptFunction = { link = "ykm22Fg1" },
        purescriptConditional = { link = "ykm22Orange" },
        purescriptBacktick = { link = "ykm22Orange" },
        coffeeExtendedOp = { link = "ykm22Fg3" },
        coffeeSpecialOp = { link = "ykm22Fg3" },
        coffeeCurly = { link = "ykm22Orange" },
        coffeeParen = { link = "ykm22Fg3" },
        coffeeBracket = { link = "ykm22Orange" },
        rubyStringDelimiter = { link = "ykm22Green" },
        rubyInterpolationDelimiter = { link = "ykm22Aqua" },
        rubyDefinedOperator = { link = "rubyKeyword" },
        objcTypeModifier = { link = "ykm22Red" },
        objcDirective = { link = "ykm22Blue" },
        goDirective = { link = "ykm22Aqua" },
        goConstants = { link = "ykm22Purple" },
        goDeclaration = { link = "ykm22Red" },
        goDeclType = { link = "ykm22Blue" },
        goBuiltins = { link = "ykm22Orange" },
        luaIn = { link = "ykm22Red" },
        luaFunction = { link = "ykm22Red" },
        luaTable = { link = "ykm22Orange" },
        moonSpecialOp = { link = "ykm22Fg3" },
        moonExtendedOp = { link = "ykm22Fg3" },
        moonFunction = { link = "ykm22Fg3" },
        moonObject = { link = "ykm22Yellow" },
        javaAnnotation = { link = "ykm22Blue" },
        javaDocTags = { link = "ykm22Aqua" },
        javaCommentTitle = { link = "vimCommentTitle" },
        javaParen = { link = "ykm22Fg3" },
        javaParen1 = { link = "ykm22Fg3" },
        javaParen2 = { link = "ykm22Fg3" },
        javaParen3 = { link = "ykm22Fg3" },
        javaParen4 = { link = "ykm22Fg3" },
        javaParen5 = { link = "ykm22Fg3" },
        javaOperator = { link = "ykm22Orange" },
        javaVarArg = { link = "ykm22Green" },
        elixirDocString = { link = "Comment" },
        elixirStringDelimiter = { link = "ykm22Green" },
        elixirInterpolationDelimiter = { link = "ykm22Aqua" },
        elixirModuleDeclaration = { link = "ykm22Yellow" },
        scalaNameDefinition = { link = "ykm22Fg1" },
        scalaCaseFollowing = { link = "ykm22Fg1" },
        scalaCapitalWord = { link = "ykm22Fg1" },
        scalaTypeExtension = { link = "ykm22Fg1" },
        scalaKeyword = { link = "ykm22Red" },
        scalaKeywordModifier = { link = "ykm22Red" },
        scalaSpecial = { link = "ykm22Aqua" },
        scalaOperator = { link = "ykm22Fg1" },
        scalaTypeDeclaration = { link = "ykm22Yellow" },
        scalaTypeTypePostDeclaration = { link = "ykm22Yellow" },
        scalaInstanceDeclaration = { link = "ykm22Fg1" },
        scalaInterpolation = { link = "ykm22Aqua" },
        markdownItalic = { fg = colors.fg3, italic = true },
        markdownBold = { fg = colors.fg3, bold = config.bold },
        markdownBoldItalic = {
            fg = colors.fg3,
            bold = config.bold,
            italic = true,
        },
        markdownH1 = { link = "ykm22GreenBold" },
        markdownH2 = { link = "ykm22GreenBold" },
        markdownH3 = { link = "ykm22YellowBold" },
        markdownH4 = { link = "ykm22YellowBold" },
        markdownH5 = { link = "ykm22Yellow" },
        markdownH6 = { link = "ykm22Yellow" },
        markdownCode = { link = "ykm22Aqua" },
        markdownCodeBlock = { link = "ykm22Aqua" },
        markdownCodeDelimiter = { link = "ykm22Aqua" },
        markdownBlockquote = { link = "ykm22Gray" },
        markdownListMarker = { link = "ykm22Gray" },
        markdownOrderedListMarker = { link = "ykm22Gray" },
        markdownRule = { link = "ykm22Gray" },
        markdownHeadingRule = { link = "ykm22Gray" },
        markdownUrlDelimiter = { link = "ykm22Fg3" },
        markdownLinkDelimiter = { link = "ykm22Fg3" },
        markdownLinkTextDelimiter = { link = "ykm22Fg3" },
        markdownHeadingDelimiter = { link = "ykm22Orange" },
        markdownUrl = { link = "ykm22Purple" },
        markdownUrlTitleDelimiter = { link = "ykm22Green" },
        markdownLinkText = { fg = colors.gray, underline = config.underline },
        markdownIdDeclaration = { link = "markdownLinkText" },
        haskellType = { link = "ykm22Blue" },
        haskellIdentifier = { link = "ykm22Aqua" },
        haskellSeparator = { link = "ykm22Fg4" },
        haskellDelimiter = { link = "ykm22Orange" },
        haskellOperators = { link = "ykm22Purple" },
        haskellBacktick = { link = "ykm22Orange" },
        haskellStatement = { link = "ykm22Purple" },
        haskellConditional = { link = "ykm22Purple" },
        haskellLet = { link = "ykm22Red" },
        haskellDefault = { link = "ykm22Red" },
        haskellWhere = { link = "ykm22Red" },
        haskellBottom = { link = "ykm22RedBold" },
        haskellImportKeywords = { link = "ykm22PurpleBold" },
        haskellDeclKeyword = { link = "ykm22Orange" },
        haskellDecl = { link = "ykm22Orange" },
        haskellDeriving = { link = "ykm22Purple" },
        haskellAssocType = { link = "ykm22Aqua" },
        haskellNumber = { link = "ykm22Aqua" },
        haskellPragma = { link = "ykm22RedBold" },
        haskellTH = { link = "ykm22AquaBold" },
        haskellForeignKeywords = { link = "ykm22Green" },
        haskellKeyword = { link = "ykm22Red" },
        haskellFloat = { link = "ykm22Aqua" },
        haskellInfix = { link = "ykm22Purple" },
        haskellQuote = { link = "ykm22GreenBold" },
        haskellShebang = { link = "ykm22YellowBold" },
        haskellLiquid = { link = "ykm22PurpleBold" },
        haskellQuasiQuoted = { link = "ykm22BlueBold" },
        haskellRecursiveDo = { link = "ykm22Purple" },
        haskellQuotedType = { link = "ykm22Red" },
        haskellPreProc = { link = "ykm22Fg4" },
        haskellTypeRoles = { link = "ykm22RedBold" },
        haskellTypeForall = { link = "ykm22Red" },
        haskellPatternKeyword = { link = "ykm22Blue" },
        jsonKeyword = { link = "ykm22Green" },
        jsonQuote = { link = "ykm22Green" },
        jsonBraces = { link = "ykm22Fg1" },
        jsonString = { link = "ykm22Fg1" },
        mailQuoted1 = { link = "ykm22Aqua" },
        mailQuoted2 = { link = "ykm22Purple" },
        mailQuoted3 = { link = "ykm22Yellow" },
        mailQuoted4 = { link = "ykm22Green" },
        mailQuoted5 = { link = "ykm22Red" },
        mailQuoted6 = { link = "ykm22Orange" },
        mailSignature = { link = "Comment" },
        csBraces = { link = "ykm22Fg1" },
        csEndColon = { link = "ykm22Fg1" },
        csLogicSymbols = { link = "ykm22Fg1" },
        csParens = { link = "ykm22Fg3" },
        csOpSymbols = { link = "ykm22Fg3" },
        csInterpolationDelimiter = { link = "ykm22Fg3" },
        csInterpolationAlignDel = { link = "ykm22AquaBold" },
        csInterpolationFormat = { link = "ykm22Aqua" },
        csInterpolationFormatDel = { link = "ykm22AquaBold" },
        rustSigil = { link = "ykm22Orange" },
        rustEscape = { link = "ykm22Aqua" },
        rustStringContinuation = { link = "ykm22Aqua" },
        rustEnum = { link = "ykm22Aqua" },
        rustStructure = { link = "ykm22Aqua" },
        rustModPathSep = { link = "ykm22Fg2" },
        rustCommentLineDoc = { link = "Comment" },
        rustDefault = { link = "ykm22Aqua" },
        ocamlOperator = { link = "ykm22Fg1" },
        ocamlKeyChar = { link = "ykm22Orange" },
        ocamlArrow = { link = "ykm22Orange" },
        ocamlInfixOpKeyword = { link = "ykm22Red" },
        ocamlConstructor = { link = "ykm22Orange" },
        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "ykm22Fg1" },
        LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
        LspSagaLspFinderBorder = { link = "ykm22Fg1" },
        LspSagaAutoPreview = { link = "ykm22Orange" },
        TargetWord = { fg = colors.blue, bold = config.bold },
        FinderSeparator = { link = "ykm22Aqua" },
        LspSagaDefPreviewBorder = { link = "ykm22Blue" },
        LspSagaHoverBorder = { link = "ykm22Orange" },
        LspSagaRenameBorder = { link = "ykm22Blue" },
        LspSagaDiagnosticSource = { link = "ykm22Orange" },
        LspSagaDiagnosticBorder = { link = "ykm22Purple" },
        LspSagaDiagnosticHeader = { link = "ykm22Green" },
        LspSagaSignatureHelpBorder = { link = "ykm22Green" },
        SagaShadow = { link = "ykm22Bg0" },
        DashboardShortCut = { link = "ykm22Orange" },
        DashboardHeader = { link = "ykm22Aqua" },
        DashboardCenter = { link = "ykm22Yellow" },
        DashboardFooter = { fg = colors.purple, italic = true },
        MasonHighlight = { link = "ykm22Aqua" },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
        MasonHighlightBlockBold = {
            fg = colors.bg0,
            bg = colors.blue,
            bold = true,
        },
        MasonHighlightSecondary = { fg = colors.yellow },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
        MasonHighlightBlockBoldSecondary = {
            fg = colors.bg0,
            bg = colors.yellow,
            bold = true,
        },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
        LspInlayHint = { link = "comment" },
        CarbonFile = { link = "ykm22Fg1" },
        CarbonExe = { link = "ykm22Yellow" },
        CarbonSymlink = { link = "ykm22Aqua" },
        CarbonBrokenSymlink = { link = "ykm22Red" },
        CarbonIndicator = { link = "ykm22Gray" },
        CarbonDanger = { link = "ykm22Red" },
        CarbonPending = { link = "ykm22Yellow" },
        NoiceCursor = { link = "TermCursor" },
        NotifyDEBUGBorder = { link = "ykm22Blue" },
        NotifyDEBUGIcon = { link = "ykm22Blue" },
        NotifyDEBUGTitle = { link = "ykm22Blue" },
        NotifyERRORBorder = { link = "ykm22Red" },
        NotifyERRORIcon = { link = "ykm22Red" },
        NotifyERRORTitle = { link = "ykm22Red" },
        NotifyINFOBorder = { link = "ykm22Aqua" },
        NotifyINFOIcon = { link = "ykm22Aqua" },
        NotifyINFOTitle = { link = "ykm22Aqua" },
        NotifyTRACEBorder = { link = "ykm22Green" },
        NotifyTRACEIcon = { link = "ykm22Green" },
        NotifyTRACETitle = { link = "ykm22Green" },
        NotifyWARNBorder = { link = "ykm22Yellow" },
        NotifyWARNIcon = { link = "ykm22Yellow" },
        NotifyWARNTitle = { link = "ykm22Yellow" },
        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },
        TSRainbowRed = { fg = colors.red },
        TSRainbowOrange = { fg = colors.orange },
        TSRainbowYellow = { fg = colors.yellow },
        TSRainbowGreen = { fg = colors.green },
        TSRainbowBlue = { fg = colors.blue },
        TSRainbowViolet = { fg = colors.purple },
        TSRainbowCyan = { fg = colors.cyan },
        DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
        DapUIBreakpointsCurrentLine = { link = "ykm22Yellow" },
        DapUIBreakpointsDisabledLine = { link = "ykm22Gray" },
        DapUIBreakpointsInfo = { link = "ykm22Aqua" },
        DapUIBreakpointsLine = { link = "ykm22Yellow" },
        DapUIBreakpointsPath = { link = "ykm22Blue" },
        DapUICurrentFrameName = { link = "ykm22Purple" },
        DapUIDecoration = { link = "ykm22Purple" },
        DapUIEndofBuffer = { link = "ykm22Bg2" },
        DapUIFloatBorder = { link = "ykm22Aqua" },
        DapUILineNumber = { link = "ykm22Yellow" },
        DapUIModifiedValue = { link = "ykm22Red" },
        DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green, bg = colors.bg1 },
        DapUIScope = { link = "ykm22Blue" },
        DapUISource = { link = "ykm22Fg1" },
        DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
        DapUIStop = { fg = colors.red, bg = colors.bg1 },
        DapUIStoppedThread = { link = "ykm22Blue" },
        DapUIThread = { link = "ykm22Blue" },
        DapUIType = { link = "ykm22Orange" },
        DapUIUnavailable = { link = "ykm22Gray" },
        DapUIWatchesEmpty = { link = "ykm22Gray" },
        DapUIWatchesError = { link = "ykm22Red" },
        DapUIWatchesValue = { link = "ykm22Yellow" },
        DapUIWinSelect = { link = "ykm22Yellow" },
        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },
        DiffviewStatusModified = { link = "ykm22GreenBold" },
        DiffviewFilePanelInsertions = { link = "ykm22GreenBold" },
        DiffviewFilePanelDeletions = { link = "ykm22RedBold" },
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "ykm22Fg1" },
        ["@punctuation.bracket"] = { link = "ykm22Fg2" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@character"] = { link = "String" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { fg = p.bright_red },
        ["@number"] = { link = "ykm22Green" },
        ["@float"] = { link = "ykm22Green" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "ykm22Red" },
        ["@parameter"] = { fg = "#b9c0b9" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.operator"] = { link = "ykm22Red" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "ykm22Red" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "ykm22Red" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "ykm22Fg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@namespace"] = { link = "ykm22Fg1" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "ykm22Fg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "ykm22Green" },
        ["@text.todo.unchecked"] = { link = "ykm22Gray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = {
            fg = colors.fg0,
            bg = colors.red,
            bold = config.bold,
        },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { fg = p.light_green },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },
    }

    for group, hl in pairs(config.overrides) do
        if groups[group] then
            -- "link" should not mix with other configs (:h hi-link)
            groups[group].link = nil
        end

        groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
    end

    return groups
end

---@param config ykm22Config?
ykm22.setup = function(config)
    ykm22.config = vim.tbl_deep_extend("force", ykm22.config, config or {})
end

--- main load function
ykm22.load = function()
    if vim.version().minor < 8 then
        vim.notify_once("you must use neovim 0.8 or higher")
        return
    end

    -- reset colors
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end
    vim.g.colors_name = "ykm22-theme"
    vim.o.termguicolors = true

    local groups = get_groups()

    -- add highlights
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end
ykm22.load()
ykm22.setup()


---@class COLORS
---@field fuck string
---@field dark0_hard string
---@field dark0 string
---@field dark0_soft string
---@field dark1 string
---@field dark2 string
---@field dark3 string
---@field dark4 string
---@field light0_hard string
---@field light0 string
---@field light0_soft string
---@field light1 string
---@field light2 string
---@field light3 string
---@field light4 string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_purple string
---@field bright_aqua string
---@field bright_orange string
---@field neutral_red string
---@field neutral_green string
---@field neutral_yellow string
---@field neutral_blue string
---@field neutral_purple string
---@field neutral_aqua string
---@field neutral_orange string
---@field faded_red string
---@field faded_green string
---@field faded_yellow string
---@field faded_blue string
---@field faded_purple string
---@field faded_aqua string
---@field faded_orange string
---@field dark_red_hard string
---@field dark_red string
---@field dark_red_soft string
---@field light_red_hard string
---@field light_red string
---@field light_red_soft string
---@field dark_green_hard string
---@field dark_green string
---@field dark_green_soft string
---@field light_green_hard string
---@field light_green string
---@field light_green_soft string
---@field dark_aqua_hard string
---@field dark_aqua string
---@field dark_aqua_soft string
---@field light_aqua_hard string
---@field light_aqua string
---@field light_aqua_soft string
---@field gray string
---@field warm_light string
---@field rosewater string
---@field surface2 string
---@field surface1 string
---@field surface0 string
---@field flamingo string
---@field peach string
---@field subtext string
---@field overlay string
---@field term table<integer,string>

return result
